version: "3.4"

services:
  favorite-thinks:
    container_name: favorite-thinks
    build:
      context: ./favorite
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=mysql://root:root@favorite-db:3306/favorite_db
      - SECRET_KEY=my_precious
    depends_on:
      - favorite-db
    links:
      - favorite-db

  favorite-db:
    restart: always
    container_name: favorite-db
    build:
      context: ./favorite/project/db
      dockerfile: Dockerfile
    ports:
      - 33306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASES=favorite_db
      - MYSQL_USER=favorite
      - MYSQL_PASSWORD=test1234